SELECT 
	D.NOME
	,E.NOME
	,C.NOME
	,C.ESTOQUE		AS ESTOQUE_ATUAL
	,C.PRECO
FROM ITENS_PEDIDO A
JOIN PEDIDOS      B ON A.PEDIDO   = B.PEDIDO
JOIN PRODUTOS	  C ON A.PRODUTO  = C.PRODUTO
JOIN CLIENTES     D ON B.CLIENTE  = D.CLIENTE
JOIN VENDEDORES   E ON B.VENDEDOR = E.VENDEDOR
WHERE A.PEDIDO = 31
